//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxInformation.Models
{
    using System;
    using System.Collections.Generic;

    public partial class OrgCustomize
    {
        public int Id { get; set; }
        public int OrgId { get; set; }
        public Nullable<bool> IsXeroEnabled { get; set; }
        public Nullable<bool> ShowCustomisedBooking { get; set; }
        public Nullable<bool> ShowSiteSetupNetwork { get; set; }
        public Nullable<bool> IsSubsidyEnabled { get; set; }
        public string SchoolInfo { get; set; }
        public string Ethinicity { get; set; }
        public string TermsAndCondition { get; set; }
        public string ChildSignoutMethod { get; set; }
        public string XML { get; set; }
        public string URL { get; set; }
        public Nullable<bool> ShowHolidayProgram { get; set; }
        public Nullable<bool> ShowSpecialProgram { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<bool> ShowStaffTitles { get; set; }
        public Nullable<bool> ShowDriverRole { get; set; }
        public Nullable<bool> ShowProgMgrRole { get; set; }
        public Nullable<bool> AllowBookOnWeekend { get; set; }
        public Nullable<bool> Is24HourClockFormat { get; set; }
        public Nullable<bool> ShowSingleRate { get; set; }
        public Nullable<bool> ShowImageOnBookingTemp { get; set; }
        public Nullable<bool> CanMarkAsPaid { get; set; }
        public Nullable<bool> ShowChildNoteOnMgmt { get; set; }
        public string HowHear { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<bool> ShowMyStats { get; set; }
        public Nullable<bool> ShowNetworkStats { get; set; }
        public Nullable<bool> ShowAchievementTracking { get; set; }
        public Nullable<bool> ShowSiteSelectionOnEnrollment { get; set; }
        public Nullable<bool> HideDateRangeBooking { get; set; }
        public Nullable<bool> ShowDrivingLicence { get; set; }
        public Nullable<bool> ShowPermanentKeyOnBookingType { get; set; }
        public Nullable<bool> IsClassEnabled { get; set; }
        public Nullable<decimal> TimezoneOffset { get; set; }
        public Nullable<bool> ShowOscarIntendedAtBooking { get; set; }
        public Nullable<bool> ExcludeDaysChargeable { get; set; }
        public Nullable<bool> DisableWINZonForm { get; set; }
        public Nullable<bool> AllowIncompleteExpressRegister { get; set; }
        public string Timezone { get; set; }
        public Nullable<int> FinanceModuleType { get; set; }
        public string CurrencySymbol { get; set; }
        public string CountryCode { get; set; }
        public Nullable<bool> ShowBillingSetting { get; set; }
        public string TaxName { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string Culture { get; set; }
        public string SubsidySystem { get; set; }
        public string SubsidyLabel { get; set; }
        public Nullable<bool> ShowExtraFees { get; set; }
        public Nullable<bool> AllowTemplateSameInvPeriodPricing { get; set; }

        public virtual Org Org { get; set; }
        public List<OrgIDDropDown> OrgIDDropDownProp { get; set; }
    }

    public class OrgIDDropDown
    {
        public string OrgName { get; set; }
    }
       
}
